import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <div className={styles.description}>
                <p>
                    <code className={styles.code}>happy hacking!!</code>
                </p>
                <div>
                    <a
                    href="https://exon.kr"
                    target="_blank"
                    rel="noopener noreferrer"
                    >
                    By EXON
                    </a>
                </div>
            </div>
        </main>

        <div className={styles.center}>
            <h1 className={styles.welcome}>
                Community
            </h1>
        </div>

        <main className={styles.main}>
            <div className={styles.grid}>
                <a
                    href="/signup"
                    className={styles.card}
                    rel="noopener noreferrer"
                >
                    <h2 className={inter.className}>
                        Sign Up <span>-&gt;</span>
                    </h2>
                    <p className={inter.className}>
                        Sign up and enjoy my site!
                    </p>
                </a>

                <a
                    href="/login"
                    className={styles.card}
                    rel="noopener noreferrer"
                >
                    <h2 className={inter.className}>
                        Login <span>-&gt;</span>
                    </h2>
                    <p className={inter.className}>
                        Write your own posts and share them with the world!
                    </p>
                </a>

                <a
                    href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    className={styles.card}
                    rel="noopener noreferrer"
                >
                    <h2 className={inter.className}>
                        Community <span>-&gt;</span>
                    </h2>
                    <p className={inter.className}>
                        Chat with your friends and strangers.
                    </p>
                </a>

                <a
                    href="https://exon.kr"
                    className={styles.card}
                    rel="noopener noreferrer"
                >
                    <h2 className={inter.className}>
                        SiHyeok <span>-&gt;</span>
                    </h2>
                    <p className={inter.className}>
                        Do you want to know more about me?
                    </p>
                </a>
            </div>
        </main>
        </>
    )
}
