import React, { useState, useCallback } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { METHODS } from 'http'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [inputs, setInputs] = useState({
        username: '',
        password: ''
    })

    const { username, password } = inputs

    const onChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        console.log(e.target.value)
        const { value, name } = e.target
        setInputs({
            ...inputs,
            [name]: value
        })
        console.log(username)
    }, [])

    const onClick = useCallback(async (e: React.MouseEvent<HTMLButtonElement>) => {
        console.log(username, password)
        const res = await fetch(`/api/signup?username=${username}&password=${password}`, {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
            },
            
        })
        const json = await res.json()
        console.log(json)
        json.success ? alert('Success!') : alert('Failed!')
    }, [])

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <div className={styles.description}>
                <p>
                    <code className={styles.code}>happy hacking!!</code>
                </p>
                <div>
                    <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    >
                    By EXON
                    </a>
                </div>
            </div>
        </main>

        <div className={styles.center}>
            <h1 className={styles.welcome}>
                Sign Up
            </h1>
            <p className={inter.className}>INSERT INTO user VALUES (id, "{username}", "{password}")</p>
            <form>
                <input className={inter.className} type='text' placeholder='username' onChange={onChange} name='username' value={username}></input>
                <input className={inter.className} type='text' placeholder='password' onChange={onChange} name='password' value={password}></input>
                <button type='submit' className={inter.className} onClick={onClick}>Sign Up</button>
            </form>
        </div>
        </>
    )
}
